/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const PageLazyRouteImport = createFileRoute('/')()
const TypographyPageLazyRouteImport = createFileRoute('/typography/')()
const TooltipPageLazyRouteImport = createFileRoute('/tooltip/')()
const TextareaPageLazyRouteImport = createFileRoute('/textarea/')()
const TabsPageLazyRouteImport = createFileRoute('/tabs/')()
const SwitchPageLazyRouteImport = createFileRoute('/switch/')()
const SpinnerPageLazyRouteImport = createFileRoute('/spinner/')()
const SonnerPageLazyRouteImport = createFileRoute('/sonner/')()
const SliderPageLazyRouteImport = createFileRoute('/slider/')()
const SkeletonPageLazyRouteImport = createFileRoute('/skeleton/')()
const SidebarPageLazyRouteImport = createFileRoute('/sidebar/')()
const SeparatorPageLazyRouteImport = createFileRoute('/separator/')()
const SelectPageLazyRouteImport = createFileRoute('/select/')()
const RadioGroupPageLazyRouteImport = createFileRoute('/radio-group/')()
const PopoverPageLazyRouteImport = createFileRoute('/popover/')()
const NativeSelectPageLazyRouteImport = createFileRoute('/native-select/')()
const LinkPageLazyRouteImport = createFileRoute('/link/')()
const KbdPageLazyRouteImport = createFileRoute('/kbd/')()
const ItemPageLazyRouteImport = createFileRoute('/item/')()
const InputPageLazyRouteImport = createFileRoute('/input/')()
const InputGroupPageLazyRouteImport = createFileRoute('/input-group/')()
const FieldPageLazyRouteImport = createFileRoute('/field/')()
const EmptyPageLazyRouteImport = createFileRoute('/empty/')()
const DialogPageLazyRouteImport = createFileRoute('/dialog/')()
const ComboboxPageLazyRouteImport = createFileRoute('/combobox/')()
const CollapsiblePageLazyRouteImport = createFileRoute('/collapsible/')()
const CheckboxPageLazyRouteImport = createFileRoute('/checkbox/')()
const CardPageLazyRouteImport = createFileRoute('/card/')()
const ButtonPageLazyRouteImport = createFileRoute('/button/')()
const ButtonGroupPageLazyRouteImport = createFileRoute('/button-group/')()
const BadgePageLazyRouteImport = createFileRoute('/badge/')()
const AvatarPageLazyRouteImport = createFileRoute('/avatar/')()
const AlertPageLazyRouteImport = createFileRoute('/alert/')()
const AlertDialogPageLazyRouteImport = createFileRoute('/alert-dialog/')()

const PageLazyRoute = PageLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/page.lazy').then((d) => d.Route))
const TypographyPageLazyRoute = TypographyPageLazyRouteImport.update({
  id: '/typography/',
  path: '/typography/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/typography/page.lazy').then((d) => d.Route),
)
const TooltipPageLazyRoute = TooltipPageLazyRouteImport.update({
  id: '/tooltip/',
  path: '/tooltip/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tooltip/page.lazy').then((d) => d.Route))
const TextareaPageLazyRoute = TextareaPageLazyRouteImport.update({
  id: '/textarea/',
  path: '/textarea/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/textarea/page.lazy').then((d) => d.Route))
const TabsPageLazyRoute = TabsPageLazyRouteImport.update({
  id: '/tabs/',
  path: '/tabs/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tabs/page.lazy').then((d) => d.Route))
const SwitchPageLazyRoute = SwitchPageLazyRouteImport.update({
  id: '/switch/',
  path: '/switch/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/switch/page.lazy').then((d) => d.Route))
const SpinnerPageLazyRoute = SpinnerPageLazyRouteImport.update({
  id: '/spinner/',
  path: '/spinner/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/spinner/page.lazy').then((d) => d.Route))
const SonnerPageLazyRoute = SonnerPageLazyRouteImport.update({
  id: '/sonner/',
  path: '/sonner/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sonner/page.lazy').then((d) => d.Route))
const SliderPageLazyRoute = SliderPageLazyRouteImport.update({
  id: '/slider/',
  path: '/slider/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/slider/page.lazy').then((d) => d.Route))
const SkeletonPageLazyRoute = SkeletonPageLazyRouteImport.update({
  id: '/skeleton/',
  path: '/skeleton/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/skeleton/page.lazy').then((d) => d.Route))
const SidebarPageLazyRoute = SidebarPageLazyRouteImport.update({
  id: '/sidebar/',
  path: '/sidebar/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sidebar/page.lazy').then((d) => d.Route))
const SeparatorPageLazyRoute = SeparatorPageLazyRouteImport.update({
  id: '/separator/',
  path: '/separator/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/separator/page.lazy').then((d) => d.Route),
)
const SelectPageLazyRoute = SelectPageLazyRouteImport.update({
  id: '/select/',
  path: '/select/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/select/page.lazy').then((d) => d.Route))
const RadioGroupPageLazyRoute = RadioGroupPageLazyRouteImport.update({
  id: '/radio-group/',
  path: '/radio-group/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/radio-group/page.lazy').then((d) => d.Route),
)
const PopoverPageLazyRoute = PopoverPageLazyRouteImport.update({
  id: '/popover/',
  path: '/popover/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/popover/page.lazy').then((d) => d.Route))
const NativeSelectPageLazyRoute = NativeSelectPageLazyRouteImport.update({
  id: '/native-select/',
  path: '/native-select/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/native-select/page.lazy').then((d) => d.Route),
)
const LinkPageLazyRoute = LinkPageLazyRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/link/page.lazy').then((d) => d.Route))
const KbdPageLazyRoute = KbdPageLazyRouteImport.update({
  id: '/kbd/',
  path: '/kbd/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kbd/page.lazy').then((d) => d.Route))
const ItemPageLazyRoute = ItemPageLazyRouteImport.update({
  id: '/item/',
  path: '/item/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/item/page.lazy').then((d) => d.Route))
const InputPageLazyRoute = InputPageLazyRouteImport.update({
  id: '/input/',
  path: '/input/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/input/page.lazy').then((d) => d.Route))
const InputGroupPageLazyRoute = InputGroupPageLazyRouteImport.update({
  id: '/input-group/',
  path: '/input-group/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/input-group/page.lazy').then((d) => d.Route),
)
const FieldPageLazyRoute = FieldPageLazyRouteImport.update({
  id: '/field/',
  path: '/field/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/field/page.lazy').then((d) => d.Route))
const EmptyPageLazyRoute = EmptyPageLazyRouteImport.update({
  id: '/empty/',
  path: '/empty/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/empty/page.lazy').then((d) => d.Route))
const DialogPageLazyRoute = DialogPageLazyRouteImport.update({
  id: '/dialog/',
  path: '/dialog/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dialog/page.lazy').then((d) => d.Route))
const ComboboxPageLazyRoute = ComboboxPageLazyRouteImport.update({
  id: '/combobox/',
  path: '/combobox/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/combobox/page.lazy').then((d) => d.Route))
const CollapsiblePageLazyRoute = CollapsiblePageLazyRouteImport.update({
  id: '/collapsible/',
  path: '/collapsible/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/collapsible/page.lazy').then((d) => d.Route),
)
const CheckboxPageLazyRoute = CheckboxPageLazyRouteImport.update({
  id: '/checkbox/',
  path: '/checkbox/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/checkbox/page.lazy').then((d) => d.Route))
const CardPageLazyRoute = CardPageLazyRouteImport.update({
  id: '/card/',
  path: '/card/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/card/page.lazy').then((d) => d.Route))
const ButtonPageLazyRoute = ButtonPageLazyRouteImport.update({
  id: '/button/',
  path: '/button/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/button/page.lazy').then((d) => d.Route))
const ButtonGroupPageLazyRoute = ButtonGroupPageLazyRouteImport.update({
  id: '/button-group/',
  path: '/button-group/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/button-group/page.lazy').then((d) => d.Route),
)
const BadgePageLazyRoute = BadgePageLazyRouteImport.update({
  id: '/badge/',
  path: '/badge/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/badge/page.lazy').then((d) => d.Route))
const AvatarPageLazyRoute = AvatarPageLazyRouteImport.update({
  id: '/avatar/',
  path: '/avatar/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/avatar/page.lazy').then((d) => d.Route))
const AlertPageLazyRoute = AlertPageLazyRouteImport.update({
  id: '/alert/',
  path: '/alert/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alert/page.lazy').then((d) => d.Route))
const AlertDialogPageLazyRoute = AlertDialogPageLazyRouteImport.update({
  id: '/alert-dialog/',
  path: '/alert-dialog/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/alert-dialog/page.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof PageLazyRoute
  '/alert-dialog/': typeof AlertDialogPageLazyRoute
  '/alert/': typeof AlertPageLazyRoute
  '/avatar/': typeof AvatarPageLazyRoute
  '/badge/': typeof BadgePageLazyRoute
  '/button-group/': typeof ButtonGroupPageLazyRoute
  '/button/': typeof ButtonPageLazyRoute
  '/card/': typeof CardPageLazyRoute
  '/checkbox/': typeof CheckboxPageLazyRoute
  '/collapsible/': typeof CollapsiblePageLazyRoute
  '/combobox/': typeof ComboboxPageLazyRoute
  '/dialog/': typeof DialogPageLazyRoute
  '/empty/': typeof EmptyPageLazyRoute
  '/field/': typeof FieldPageLazyRoute
  '/input-group/': typeof InputGroupPageLazyRoute
  '/input/': typeof InputPageLazyRoute
  '/item/': typeof ItemPageLazyRoute
  '/kbd/': typeof KbdPageLazyRoute
  '/link/': typeof LinkPageLazyRoute
  '/native-select/': typeof NativeSelectPageLazyRoute
  '/popover/': typeof PopoverPageLazyRoute
  '/radio-group/': typeof RadioGroupPageLazyRoute
  '/select/': typeof SelectPageLazyRoute
  '/separator/': typeof SeparatorPageLazyRoute
  '/sidebar/': typeof SidebarPageLazyRoute
  '/skeleton/': typeof SkeletonPageLazyRoute
  '/slider/': typeof SliderPageLazyRoute
  '/sonner/': typeof SonnerPageLazyRoute
  '/spinner/': typeof SpinnerPageLazyRoute
  '/switch/': typeof SwitchPageLazyRoute
  '/tabs/': typeof TabsPageLazyRoute
  '/textarea/': typeof TextareaPageLazyRoute
  '/tooltip/': typeof TooltipPageLazyRoute
  '/typography/': typeof TypographyPageLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof PageLazyRoute
  '/alert-dialog': typeof AlertDialogPageLazyRoute
  '/alert': typeof AlertPageLazyRoute
  '/avatar': typeof AvatarPageLazyRoute
  '/badge': typeof BadgePageLazyRoute
  '/button-group': typeof ButtonGroupPageLazyRoute
  '/button': typeof ButtonPageLazyRoute
  '/card': typeof CardPageLazyRoute
  '/checkbox': typeof CheckboxPageLazyRoute
  '/collapsible': typeof CollapsiblePageLazyRoute
  '/combobox': typeof ComboboxPageLazyRoute
  '/dialog': typeof DialogPageLazyRoute
  '/empty': typeof EmptyPageLazyRoute
  '/field': typeof FieldPageLazyRoute
  '/input-group': typeof InputGroupPageLazyRoute
  '/input': typeof InputPageLazyRoute
  '/item': typeof ItemPageLazyRoute
  '/kbd': typeof KbdPageLazyRoute
  '/link': typeof LinkPageLazyRoute
  '/native-select': typeof NativeSelectPageLazyRoute
  '/popover': typeof PopoverPageLazyRoute
  '/radio-group': typeof RadioGroupPageLazyRoute
  '/select': typeof SelectPageLazyRoute
  '/separator': typeof SeparatorPageLazyRoute
  '/sidebar': typeof SidebarPageLazyRoute
  '/skeleton': typeof SkeletonPageLazyRoute
  '/slider': typeof SliderPageLazyRoute
  '/sonner': typeof SonnerPageLazyRoute
  '/spinner': typeof SpinnerPageLazyRoute
  '/switch': typeof SwitchPageLazyRoute
  '/tabs': typeof TabsPageLazyRoute
  '/textarea': typeof TextareaPageLazyRoute
  '/tooltip': typeof TooltipPageLazyRoute
  '/typography': typeof TypographyPageLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageLazyRoute
  '/alert-dialog/': typeof AlertDialogPageLazyRoute
  '/alert/': typeof AlertPageLazyRoute
  '/avatar/': typeof AvatarPageLazyRoute
  '/badge/': typeof BadgePageLazyRoute
  '/button-group/': typeof ButtonGroupPageLazyRoute
  '/button/': typeof ButtonPageLazyRoute
  '/card/': typeof CardPageLazyRoute
  '/checkbox/': typeof CheckboxPageLazyRoute
  '/collapsible/': typeof CollapsiblePageLazyRoute
  '/combobox/': typeof ComboboxPageLazyRoute
  '/dialog/': typeof DialogPageLazyRoute
  '/empty/': typeof EmptyPageLazyRoute
  '/field/': typeof FieldPageLazyRoute
  '/input-group/': typeof InputGroupPageLazyRoute
  '/input/': typeof InputPageLazyRoute
  '/item/': typeof ItemPageLazyRoute
  '/kbd/': typeof KbdPageLazyRoute
  '/link/': typeof LinkPageLazyRoute
  '/native-select/': typeof NativeSelectPageLazyRoute
  '/popover/': typeof PopoverPageLazyRoute
  '/radio-group/': typeof RadioGroupPageLazyRoute
  '/select/': typeof SelectPageLazyRoute
  '/separator/': typeof SeparatorPageLazyRoute
  '/sidebar/': typeof SidebarPageLazyRoute
  '/skeleton/': typeof SkeletonPageLazyRoute
  '/slider/': typeof SliderPageLazyRoute
  '/sonner/': typeof SonnerPageLazyRoute
  '/spinner/': typeof SpinnerPageLazyRoute
  '/switch/': typeof SwitchPageLazyRoute
  '/tabs/': typeof TabsPageLazyRoute
  '/textarea/': typeof TextareaPageLazyRoute
  '/tooltip/': typeof TooltipPageLazyRoute
  '/typography/': typeof TypographyPageLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert-dialog/'
    | '/alert/'
    | '/avatar/'
    | '/badge/'
    | '/button-group/'
    | '/button/'
    | '/card/'
    | '/checkbox/'
    | '/collapsible/'
    | '/combobox/'
    | '/dialog/'
    | '/empty/'
    | '/field/'
    | '/input-group/'
    | '/input/'
    | '/item/'
    | '/kbd/'
    | '/link/'
    | '/native-select/'
    | '/popover/'
    | '/radio-group/'
    | '/select/'
    | '/separator/'
    | '/sidebar/'
    | '/skeleton/'
    | '/slider/'
    | '/sonner/'
    | '/spinner/'
    | '/switch/'
    | '/tabs/'
    | '/textarea/'
    | '/tooltip/'
    | '/typography/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert-dialog'
    | '/alert'
    | '/avatar'
    | '/badge'
    | '/button-group'
    | '/button'
    | '/card'
    | '/checkbox'
    | '/collapsible'
    | '/combobox'
    | '/dialog'
    | '/empty'
    | '/field'
    | '/input-group'
    | '/input'
    | '/item'
    | '/kbd'
    | '/link'
    | '/native-select'
    | '/popover'
    | '/radio-group'
    | '/select'
    | '/separator'
    | '/sidebar'
    | '/skeleton'
    | '/slider'
    | '/sonner'
    | '/spinner'
    | '/switch'
    | '/tabs'
    | '/textarea'
    | '/tooltip'
    | '/typography'
  id:
    | '__root__'
    | '/'
    | '/alert-dialog/'
    | '/alert/'
    | '/avatar/'
    | '/badge/'
    | '/button-group/'
    | '/button/'
    | '/card/'
    | '/checkbox/'
    | '/collapsible/'
    | '/combobox/'
    | '/dialog/'
    | '/empty/'
    | '/field/'
    | '/input-group/'
    | '/input/'
    | '/item/'
    | '/kbd/'
    | '/link/'
    | '/native-select/'
    | '/popover/'
    | '/radio-group/'
    | '/select/'
    | '/separator/'
    | '/sidebar/'
    | '/skeleton/'
    | '/slider/'
    | '/sonner/'
    | '/spinner/'
    | '/switch/'
    | '/tabs/'
    | '/textarea/'
    | '/tooltip/'
    | '/typography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageLazyRoute: typeof PageLazyRoute
  AlertDialogPageLazyRoute: typeof AlertDialogPageLazyRoute
  AlertPageLazyRoute: typeof AlertPageLazyRoute
  AvatarPageLazyRoute: typeof AvatarPageLazyRoute
  BadgePageLazyRoute: typeof BadgePageLazyRoute
  ButtonGroupPageLazyRoute: typeof ButtonGroupPageLazyRoute
  ButtonPageLazyRoute: typeof ButtonPageLazyRoute
  CardPageLazyRoute: typeof CardPageLazyRoute
  CheckboxPageLazyRoute: typeof CheckboxPageLazyRoute
  CollapsiblePageLazyRoute: typeof CollapsiblePageLazyRoute
  ComboboxPageLazyRoute: typeof ComboboxPageLazyRoute
  DialogPageLazyRoute: typeof DialogPageLazyRoute
  EmptyPageLazyRoute: typeof EmptyPageLazyRoute
  FieldPageLazyRoute: typeof FieldPageLazyRoute
  InputGroupPageLazyRoute: typeof InputGroupPageLazyRoute
  InputPageLazyRoute: typeof InputPageLazyRoute
  ItemPageLazyRoute: typeof ItemPageLazyRoute
  KbdPageLazyRoute: typeof KbdPageLazyRoute
  LinkPageLazyRoute: typeof LinkPageLazyRoute
  NativeSelectPageLazyRoute: typeof NativeSelectPageLazyRoute
  PopoverPageLazyRoute: typeof PopoverPageLazyRoute
  RadioGroupPageLazyRoute: typeof RadioGroupPageLazyRoute
  SelectPageLazyRoute: typeof SelectPageLazyRoute
  SeparatorPageLazyRoute: typeof SeparatorPageLazyRoute
  SidebarPageLazyRoute: typeof SidebarPageLazyRoute
  SkeletonPageLazyRoute: typeof SkeletonPageLazyRoute
  SliderPageLazyRoute: typeof SliderPageLazyRoute
  SonnerPageLazyRoute: typeof SonnerPageLazyRoute
  SpinnerPageLazyRoute: typeof SpinnerPageLazyRoute
  SwitchPageLazyRoute: typeof SwitchPageLazyRoute
  TabsPageLazyRoute: typeof TabsPageLazyRoute
  TextareaPageLazyRoute: typeof TextareaPageLazyRoute
  TooltipPageLazyRoute: typeof TooltipPageLazyRoute
  TypographyPageLazyRoute: typeof TypographyPageLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography/': {
      id: '/typography/'
      path: '/typography'
      fullPath: '/typography/'
      preLoaderRoute: typeof TypographyPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooltip/': {
      id: '/tooltip/'
      path: '/tooltip'
      fullPath: '/tooltip/'
      preLoaderRoute: typeof TooltipPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textarea/': {
      id: '/textarea/'
      path: '/textarea'
      fullPath: '/textarea/'
      preLoaderRoute: typeof TextareaPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs/': {
      id: '/tabs/'
      path: '/tabs'
      fullPath: '/tabs/'
      preLoaderRoute: typeof TabsPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch/': {
      id: '/switch/'
      path: '/switch'
      fullPath: '/switch/'
      preLoaderRoute: typeof SwitchPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spinner/': {
      id: '/spinner/'
      path: '/spinner'
      fullPath: '/spinner/'
      preLoaderRoute: typeof SpinnerPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonner/': {
      id: '/sonner/'
      path: '/sonner'
      fullPath: '/sonner/'
      preLoaderRoute: typeof SonnerPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slider/': {
      id: '/slider/'
      path: '/slider'
      fullPath: '/slider/'
      preLoaderRoute: typeof SliderPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skeleton/': {
      id: '/skeleton/'
      path: '/skeleton'
      fullPath: '/skeleton/'
      preLoaderRoute: typeof SkeletonPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebar/': {
      id: '/sidebar/'
      path: '/sidebar'
      fullPath: '/sidebar/'
      preLoaderRoute: typeof SidebarPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/separator/': {
      id: '/separator/'
      path: '/separator'
      fullPath: '/separator/'
      preLoaderRoute: typeof SeparatorPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select/': {
      id: '/select/'
      path: '/select'
      fullPath: '/select/'
      preLoaderRoute: typeof SelectPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio-group/': {
      id: '/radio-group/'
      path: '/radio-group'
      fullPath: '/radio-group/'
      preLoaderRoute: typeof RadioGroupPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popover/': {
      id: '/popover/'
      path: '/popover'
      fullPath: '/popover/'
      preLoaderRoute: typeof PopoverPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native-select/': {
      id: '/native-select/'
      path: '/native-select'
      fullPath: '/native-select/'
      preLoaderRoute: typeof NativeSelectPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link/': {
      id: '/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof LinkPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kbd/': {
      id: '/kbd/'
      path: '/kbd'
      fullPath: '/kbd/'
      preLoaderRoute: typeof KbdPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/': {
      id: '/item/'
      path: '/item'
      fullPath: '/item/'
      preLoaderRoute: typeof ItemPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input/': {
      id: '/input/'
      path: '/input'
      fullPath: '/input/'
      preLoaderRoute: typeof InputPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input-group/': {
      id: '/input-group/'
      path: '/input-group'
      fullPath: '/input-group/'
      preLoaderRoute: typeof InputGroupPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/': {
      id: '/field/'
      path: '/field'
      fullPath: '/field/'
      preLoaderRoute: typeof FieldPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty/': {
      id: '/empty/'
      path: '/empty'
      fullPath: '/empty/'
      preLoaderRoute: typeof EmptyPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/': {
      id: '/dialog/'
      path: '/dialog'
      fullPath: '/dialog/'
      preLoaderRoute: typeof DialogPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combobox/': {
      id: '/combobox/'
      path: '/combobox'
      fullPath: '/combobox/'
      preLoaderRoute: typeof ComboboxPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collapsible/': {
      id: '/collapsible/'
      path: '/collapsible'
      fullPath: '/collapsible/'
      preLoaderRoute: typeof CollapsiblePageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkbox/': {
      id: '/checkbox/'
      path: '/checkbox'
      fullPath: '/checkbox/'
      preLoaderRoute: typeof CheckboxPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/': {
      id: '/card/'
      path: '/card'
      fullPath: '/card/'
      preLoaderRoute: typeof CardPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button/': {
      id: '/button/'
      path: '/button'
      fullPath: '/button/'
      preLoaderRoute: typeof ButtonPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-group/': {
      id: '/button-group/'
      path: '/button-group'
      fullPath: '/button-group/'
      preLoaderRoute: typeof ButtonGroupPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/': {
      id: '/badge/'
      path: '/badge'
      fullPath: '/badge/'
      preLoaderRoute: typeof BadgePageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar/': {
      id: '/avatar/'
      path: '/avatar'
      fullPath: '/avatar/'
      preLoaderRoute: typeof AvatarPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/': {
      id: '/alert/'
      path: '/alert'
      fullPath: '/alert/'
      preLoaderRoute: typeof AlertPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-dialog/': {
      id: '/alert-dialog/'
      path: '/alert-dialog'
      fullPath: '/alert-dialog/'
      preLoaderRoute: typeof AlertDialogPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageLazyRoute: PageLazyRoute,
  AlertDialogPageLazyRoute: AlertDialogPageLazyRoute,
  AlertPageLazyRoute: AlertPageLazyRoute,
  AvatarPageLazyRoute: AvatarPageLazyRoute,
  BadgePageLazyRoute: BadgePageLazyRoute,
  ButtonGroupPageLazyRoute: ButtonGroupPageLazyRoute,
  ButtonPageLazyRoute: ButtonPageLazyRoute,
  CardPageLazyRoute: CardPageLazyRoute,
  CheckboxPageLazyRoute: CheckboxPageLazyRoute,
  CollapsiblePageLazyRoute: CollapsiblePageLazyRoute,
  ComboboxPageLazyRoute: ComboboxPageLazyRoute,
  DialogPageLazyRoute: DialogPageLazyRoute,
  EmptyPageLazyRoute: EmptyPageLazyRoute,
  FieldPageLazyRoute: FieldPageLazyRoute,
  InputGroupPageLazyRoute: InputGroupPageLazyRoute,
  InputPageLazyRoute: InputPageLazyRoute,
  ItemPageLazyRoute: ItemPageLazyRoute,
  KbdPageLazyRoute: KbdPageLazyRoute,
  LinkPageLazyRoute: LinkPageLazyRoute,
  NativeSelectPageLazyRoute: NativeSelectPageLazyRoute,
  PopoverPageLazyRoute: PopoverPageLazyRoute,
  RadioGroupPageLazyRoute: RadioGroupPageLazyRoute,
  SelectPageLazyRoute: SelectPageLazyRoute,
  SeparatorPageLazyRoute: SeparatorPageLazyRoute,
  SidebarPageLazyRoute: SidebarPageLazyRoute,
  SkeletonPageLazyRoute: SkeletonPageLazyRoute,
  SliderPageLazyRoute: SliderPageLazyRoute,
  SonnerPageLazyRoute: SonnerPageLazyRoute,
  SpinnerPageLazyRoute: SpinnerPageLazyRoute,
  SwitchPageLazyRoute: SwitchPageLazyRoute,
  TabsPageLazyRoute: TabsPageLazyRoute,
  TextareaPageLazyRoute: TextareaPageLazyRoute,
  TooltipPageLazyRoute: TooltipPageLazyRoute,
  TypographyPageLazyRoute: TypographyPageLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
